### ISSUE TITLE
Fill Task Status remarks with something useful

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#240]
## Summary
When running `queue get` command it returns something like:
```
 JobTasksStatus:

    Sequence: 1
    TaskName: Generate
    Status: Success
    Remarks: NULL
```

The remarks is filled with error message when the task is failed. I think it'd be better if we fill it with some useful values as well when success. The `result.ReturnValue` would be a good candidate for it.
